export const sampleProducts = [
  // 5 LUXURY MEN'S HOODIES (₹699 Offer Price, ₹899 Original Price, 22% OFF)
  {
    _id: "hoodie-new-1",
    name: "Oatmeal Cream Minimalist Vyora Chest Embroidery Hoodie",
    slug: "oatmeal-cream-minimalist-vyora-chest-embroidery-hoodie",
    description: "Ultra-soft 480GSM French terry cotton hoodie in oatmeal cream featuring high-density minimalist Vyora chest embroidery and kangaroo pocket.",
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 5.0,
    reviewsCount: 185,
    category: "Hoodies",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Oatmeal Cream", hex: "#F3EAD8" },
      { name: "Onyx Black", hex: "#0A0A0A" }
    ],
    image: "/hoodie-1.png",
    images: ["/hoodie-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Hoodies",
    fabric: "100% Heavyweight French Terry Cotton (480 GSM)",
    careInstructions: "Machine wash cold inside out, dry flat in shade.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "hoodie-new-2",
    name: "Espresso Brown Gold V Monogram Emblem Hoodie",
    slug: "espresso-brown-gold-v-monogram-emblem-hoodie",
    description: "Deep espresso brown luxury hoodie decorated with a metallic gold geometric V crest emblem on the left chest and gold-tipped drawstrings.",
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 4.9,
    reviewsCount: 142,
    category: "Hoodies",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Espresso Brown", hex: "#3B271E" },
      { name: "Gold Accent", hex: "#D4AF37" }
    ],
    image: "/hoodie-2.png",
    images: ["/hoodie-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Hoodies",
    fabric: "480GSM Heavy Organic Fleece Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "hoodie-new-3",
    name: "Olive Forest Gold V Back Monogram Heavyweight Hoodie",
    slug: "olive-forest-gold-v-back-monogram-heavyweight-hoodie",
    description: "Statement forest green heavyweight hoodie showcasing a massive metallic gold V logo back print and gold Vyora hood neck tag.",
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 5.0,
    reviewsCount: 198,
    category: "Hoodies",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Forest Olive", hex: "#2E3B2B" },
      { name: "Metallic Gold", hex: "#D4AF37" }
    ],
    image: "/hoodie-3.png",
    images: ["/hoodie-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Hoodies",
    fabric: "100% Heavy Combed French Terry (480 GSM)",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 60
  },

  // 9 LUXURY MEN'S SHIRTS (₹799 Offer Price, ₹999 Original Price, 20% OFF)
  {
    _id: "shirt-new-1",
    name: "Blue Water-Tie-Dye Silk Satin Shirt",
    slug: "blue-water-tie-dye-silk-satin-shirt",
    description: "Fluid mulberry silk satin resort shirt featuring a custom blue & white water tie-dye print with camp collar.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 124,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Ocean Tie-Dye", hex: "#4A6FA5" },
      { name: "Pure White", hex: "#FFFFFF" }
    ],
    image: "/shirt-1.png",
    images: ["/shirt-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Mulberry Silk Satin Blend",
    careInstructions: "Delicate dry clean or hand wash cold.",
    inStock: true,
    stockCount: 40
  },
  {
    _id: "shirt-new-2",
    name: "Rose Gold Marble Flow Satin Shirt",
    slug: "rose-gold-marble-flow-satin-shirt",
    description: "Opulent rose gold & cream marble swirl printed satin shirt crafted with mother-of-pearl buttons and tailored cuff lines.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 5.0,
    reviewsCount: 156,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Rose Gold Swirl", hex: "#C8A288" },
      { name: "Cream Ivory", hex: "#F3EAD8" }
    ],
    image: "/shirt-2.png",
    images: ["/shirt-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Ultra-Luster Satin Silk Cotton",
    careInstructions: "Delicate cycle cold wash, warm iron.",
    inStock: true,
    stockCount: 35
  },
  {
    _id: "shirt-new-3",
    name: "Geometric Grid Obsidian Satin Shirt",
    slug: "geometric-grid-obsidian-satin-shirt",
    description: "Contemporary obsidian black satin shirt adorned with a crisp cream geometric line grid pattern and front chest pocket.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewsCount: 92,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Obsidian Black", hex: "#111111" },
      { name: "Gold Line Accent", hex: "#D4AF37" }
    ],
    image: "/shirt-3.png",
    images: ["/shirt-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Micro-Luster Satin Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "shirt-new-4",
    name: "Monochrome Botanical Line Art Satin Shirt",
    slug: "monochrome-botanical-line-art-satin-shirt",
    description: "Sophisticated black satin shirt with all-over cream floral sketch embroidery print and relaxed modern drop shoulder.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 118,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Monochrome Black", hex: "#0A0A0A" },
      { name: "Line Art Cream", hex: "#EADCC9" }
    ],
    image: "/shirt-4.png",
    images: ["/shirt-4.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Organic Silk Touch Satin",
    careInstructions: "Hand wash cool, hang dry in shade.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "shirt-new-5",
    name: "Abstract Earth Camo Silk Resort Shirt",
    slug: "abstract-earth-camo-silk-resort-shirt",
    description: "Artisanal abstract camo print resort shirt blending earth brown, navy, and cream tones with relaxed button-down collar.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 140,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Earth Camo Multi", hex: "#8A5A3B" },
      { name: "Midnight Navy", hex: "#1A2332" }
    ],
    image: "/shirt-5.png",
    images: ["/shirt-5.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Breathable Silk-Viscose Weave",
    careInstructions: "Machine wash cold delicate.",
    inStock: true,
    stockCount: 60
  },
  {
    _id: "shirt-new-6",
    name: "Olive Palm Leaf Botanical Satin Shirt",
    slug: "olive-palm-leaf-botanical-satin-shirt",
    description: "Tropical luxury resort shirt featuring detailed olive green monstera & palm leaf illustrations on an ivory satin base.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 5.0,
    reviewsCount: 165,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Olive Palm", hex: "#4A5D3E" },
      { name: "Ivory Cream", hex: "#F3EAD8" }
    ],
    image: "/shirt-6.png",
    images: ["/shirt-6.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Micro-Luster Satin Cotton",
    careInstructions: "Delicate cycle wash, warm iron.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "shirt-new-7",
    name: "Gold Brushstroke Obsidian Satin Shirt",
    slug: "gold-brushstroke-obsidian-satin-shirt",
    description: "High-fashion black satin shirt featuring metallic gold artistic brushstroke waves and mother-of-pearl buttons.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 132,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Obsidian Gold Brush", hex: "#D4AF37" },
      { name: "Jet Black", hex: "#000000" }
    ],
    image: "/shirt-7.png",
    images: ["/shirt-7.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Premium Satin Silk Cotton",
    careInstructions: "Hand wash cold inside out.",
    inStock: true,
    stockCount: 38
  },
  {
    _id: "shirt-new-8",
    name: "Pastel Watercolor Patchwork Silk Shirt",
    slug: "pastel-watercolor-patchwork-silk-shirt",
    description: "Avant-garde resort shirt featuring soft pastel pink, teal blue, and cream watercolor block prints.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewsCount: 97,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Pastel Watercolor", hex: "#D8C5D0" },
      { name: "Teal Cream", hex: "#8DA79F" }
    ],
    image: "/shirt-8.png",
    images: ["/shirt-8.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Breathable Silk Viscose",
    careInstructions: "Delicate dry clean or hand wash cold.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "shirt-new-9",
    name: "Vintage Botanical Line Illustration Satin Shirt",
    slug: "vintage-botanical-line-illustration-satin-shirt",
    description: "Elegant off-white satin shirt adorned with detailed black vintage leaf & floral etching artwork.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 5.0,
    reviewsCount: 178,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Botanical Etching", hex: "#2B2B2B" },
      { name: "Off-White", hex: "#F5F5F0" }
    ],
    image: "/shirt-9.png",
    images: ["/shirt-9.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Organic Silk Touch Satin Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 42
  },

  // 8 MEN'S T-SHIRTS (₹599 Offer Price, ₹799 Original Price, 25% OFF)
  {
    _id: "tshirt-6",
    name: "Sky Blue Japanese Kanji Typography Wash Tee",
    slug: "sky-blue-japanese-kanji-typography-wash-tee",
    description: "Acid-washed sky blue heavy Supima cotton tee featuring minimalist front black Japanese typography artwork.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 5.0,
    reviewsCount: 184,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Acid Sky Blue", hex: "#6B9AC4" },
      { name: "Onyx Kanji", hex: "#111111" }
    ],
    image: "/tshirt-6.png",
    images: ["/tshirt-6.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Acid-Washed Supima Cotton (280 GSM)",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 70
  },
  {
    _id: "tshirt-7",
    name: "Onyx Black Ribbed Quarter-Zip Ring Polo Tee",
    slug: "onyx-black-ribbed-quarter-zip-ring-polo-tee",
    description: "Sleek jet black ribbed polo tee featuring a polished silver ring zipper pull and tailored drop shoulder fit.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 145,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Sand Beige Accent", hex: "#D4C5B9" }
    ],
    image: "/tshirt-7.png",
    images: ["/tshirt-7.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Ribbed Premium Supima Cotton",
    careInstructions: "Delicate cycle wash cold.",
    inStock: true,
    stockCount: 55
  },
  {
    _id: "tshirt-8",
    name: "Lavender Purple Mythical Dragon Back Graphic Tee",
    slug: "lavender-purple-mythical-dragon-back-graphic-tee",
    description: "Streetwear boxy tee in pastel lavender featuring a white high-density mythical dragon back illustration.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 160,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Pastel Lavender", hex: "#9B8AB8" },
      { name: "White Dragon Print", hex: "#FFFFFF" }
    ],
    image: "/tshirt-8.png",
    images: ["/tshirt-8.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Heavy Organic Cotton (260 GSM)",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 65
  },
  {
    _id: "tshirt-1",
    name: "Beige Embossed Medallion Oversized T-Shirt",
    slug: "beige-embossed-medallion-oversized-tshirt",
    description: "Premium heavy cotton oversized tee with a central 3D embossed medallion emblem, drop-shoulder cut, and vintage wash finish.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 142,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Beige Tan", hex: "#D4C5B9" },
      { name: "Charcoal Fade", hex: "#3A3A3A" }
    ],
    image: "/tshirt-1.png",
    images: ["/tshirt-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Heavyweight Supima Organic Cotton (280 GSM)",
    careInstructions: "Machine wash cold inside out, dry flat.",
    inStock: true,
    stockCount: 65
  },
  {
    _id: "tshirt-2",
    name: "Off-White Textural Monogram Crewneck",
    slug: "offwhite-textural-monogram-crewneck",
    description: "Luxury off-white crewneck tee crafted with an all-over debossed geometric monogram texture and relaxed fit silhouette.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 5.0,
    reviewsCount: 98,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ivory Cream", hex: "#F3EAD8" },
      { name: "Onyx Black", hex: "#0F0F0F" }
    ],
    image: "/tshirt-2.png",
    images: ["/tshirt-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Organic Jacquard Textured Cotton",
    careInstructions: "Delicate cold wash, warm iron.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "tshirt-3",
    name: "Cream Ribbed Quarter-Zip Polo T-Shirt",
    slug: "cream-ribbed-quarter-zip-polo-tshirt",
    description: "Sophisticated ribbed knit polo shirt featuring a polished metallic ring zipper and drop-shoulder boxy cut.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.8,
    reviewsCount: 86,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Vanilla Cream", hex: "#F5F0EB" },
      { name: "Midnight Navy", hex: "#1A2332" }
    ],
    image: "/tshirt-3.png",
    images: ["/tshirt-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "Ribbed Premium Cotton Blend",
    careInstructions: "Machine wash gentle cold.",
    inStock: true,
    stockCount: 40
  },
  {
    _id: "tshirt-4",
    name: "Earth Brown Textured Long-Sleeve Tee",
    slug: "earth-brown-textured-long-sleeve-tee",
    description: "Earth-tone brown long-sleeve tee made from micro-textured cotton with custom atelier tag branding.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 110,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Earth Brown", hex: "#784F33" },
      { name: "Stone Beige", hex: "#C5B8A5" }
    ],
    image: "/tshirt-4.png",
    images: ["/tshirt-4.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Combed Micro-Textured Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 55
  },
  {
    _id: "tshirt-5",
    name: "Abstract Pink-White Printed Oversized Tee",
    slug: "abstract-pink-white-printed-oversized-tee",
    description: "Contemporary oversized streetwear tee with all-over abstract geometric art print and relaxed drop shoulders.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 135,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Abstract Pink White", hex: "#E8C5D0" },
      { name: "Monochrome Black", hex: "#111111" }
    ],
    image: "/tshirt-5.png",
    images: ["/tshirt-5.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Premium Heavy Supima Cotton (260 GSM)",
    careInstructions: "Machine wash cool inside out.",
    inStock: true,
    stockCount: 60
  },

  // TRACK PANTS
  {
    _id: "trackpants-1",
    name: "Vanguard Heavy French Terry Track Pants",
    slug: "vanguard-heavy-french-terry-track-pants",
    description: "Relaxed tapered fit track pants with custom gold-tipped drawstrings, deep zip pockets, and ribbed ankle cuffs.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewsCount: 88,
    category: "Track Pants",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Heather Gray", hex: "#4A4A4A" }
    ],
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Track Pants",
    fabric: "420GSM Heavyweight Organic Cotton Fleece",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 50
  }
];
