export const sampleProducts = [
  // 5 NEW MEN'S SHIRTS (₹799 Offer Price, ₹999 Original Price, 20% OFF)
  {
    _id: "shirt-new-1",
    name: "Blue Water-Tie-Dye Silk Satin Shirt",
    slug: "blue-water-tie-dye-silk-satin-shirt",
    description: "Fluid mulberry silk satin resort shirt featuring a custom blue & white water tie-dye print with camp collar.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 124,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Ocean Tie-Dye", hex: "#4A6FA5" },
      { name: "Pure White", hex: "#FFFFFF" }
    ],
    image: "/shirt-1.png",
    images: ["/shirt-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Mulberry Silk Satin Blend",
    careInstructions: "Delicate dry clean or hand wash cold.",
    inStock: true,
    stockCount: 40
  },
  {
    _id: "shirt-new-2",
    name: "Rose Gold Marble Flow Satin Shirt",
    slug: "rose-gold-marble-flow-satin-shirt",
    description: "Opulent rose gold & cream marble swirl printed satin shirt crafted with mother-of-pearl buttons and tailored cuff lines.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 5.0,
    reviewsCount: 156,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Rose Gold Swirl", hex: "#C8A288" },
      { name: "Cream Ivory", hex: "#F3EAD8" }
    ],
    image: "/shirt-2.png",
    images: ["/shirt-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Ultra-Luster Satin Silk Cotton",
    careInstructions: "Delicate cycle cold wash, warm iron.",
    inStock: true,
    stockCount: 35
  },
  {
    _id: "shirt-new-3",
    name: "Geometric Grid Obsidian Satin Shirt",
    slug: "geometric-grid-obsidian-satin-shirt",
    description: "Contemporary obsidian black satin shirt adorned with a crisp cream geometric line grid pattern and front chest pocket.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewsCount: 92,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Obsidian Black", hex: "#111111" },
      { name: "Gold Line Accent", hex: "#D4AF37" }
    ],
    image: "/shirt-3.png",
    images: ["/shirt-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Micro-Luster Satin Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "shirt-new-4",
    name: "Monochrome Botanical Line Art Satin Shirt",
    slug: "monochrome-botanical-line-art-satin-shirt",
    description: "Sophisticated black satin shirt with all-over cream floral sketch embroidery print and relaxed modern drop shoulder.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 118,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Monochrome Black", hex: "#0A0A0A" },
      { name: "Line Art Cream", hex: "#EADCC9" }
    ],
    image: "/shirt-4.png",
    images: ["/shirt-4.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Organic Silk Touch Satin",
    careInstructions: "Hand wash cool, hang dry in shade.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "shirt-new-5",
    name: "Abstract Earth Camo Silk Resort Shirt",
    slug: "abstract-earth-camo-silk-resort-shirt",
    description: "Artisanal abstract camo print resort shirt blending earth brown, navy, and cream tones with relaxed button-down collar.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.9,
    reviewsCount: 140,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Earth Camo Multi", hex: "#8A5A3B" },
      { name: "Midnight Navy", hex: "#1A2332" }
    ],
    image: "/shirt-5.png",
    images: ["/shirt-5.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Breathable Silk-Viscose Weave",
    careInstructions: "Machine wash cold delicate.",
    inStock: true,
    stockCount: 60
  },

  // 5 MEN'S T-SHIRTS (₹599 Offer Price, ₹799 Original Price, 25% OFF)
  {
    _id: "tshirt-1",
    name: "Beige Embossed Medallion Oversized T-Shirt",
    slug: "beige-embossed-medallion-oversized-tshirt",
    description: "Premium heavy cotton oversized tee with a central 3D embossed medallion emblem, drop-shoulder cut, and vintage wash finish.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 142,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Beige Tan", hex: "#D4C5B9" },
      { name: "Charcoal Fade", hex: "#3A3A3A" }
    ],
    image: "/tshirt-1.png",
    images: ["/tshirt-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Heavyweight Supima Organic Cotton (280 GSM)",
    careInstructions: "Machine wash cold inside out, dry flat.",
    inStock: true,
    stockCount: 65
  },
  {
    _id: "tshirt-2",
    name: "Off-White Textural Monogram Crewneck",
    slug: "offwhite-textural-monogram-crewneck",
    description: "Luxury off-white crewneck tee crafted with an all-over debossed geometric monogram texture and relaxed fit silhouette.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 5.0,
    reviewsCount: 98,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ivory Cream", hex: "#F3EAD8" },
      { name: "Onyx Black", hex: "#0F0F0F" }
    ],
    image: "/tshirt-2.png",
    images: ["/tshirt-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Organic Jacquard Textured Cotton",
    careInstructions: "Delicate cold wash, warm iron.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "tshirt-3",
    name: "Cream Ribbed Quarter-Zip Polo T-Shirt",
    slug: "cream-ribbed-quarter-zip-polo-tshirt",
    description: "Sophisticated ribbed knit polo shirt featuring a polished metallic ring zipper and drop-shoulder boxy cut.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.8,
    reviewsCount: 86,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Vanilla Cream", hex: "#F5F0EB" },
      { name: "Midnight Navy", hex: "#1A2332" }
    ],
    image: "/tshirt-3.png",
    images: ["/tshirt-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "Ribbed Premium Cotton Blend",
    careInstructions: "Machine wash gentle cold.",
    inStock: true,
    stockCount: 40
  },
  {
    _id: "tshirt-4",
    name: "Earth Brown Textured Long-Sleeve Tee",
    slug: "earth-brown-textured-long-sleeve-tee",
    description: "Earth-tone brown long-sleeve tee made from micro-textured cotton with custom atelier tag branding.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 110,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Earth Brown", hex: "#784F33" },
      { name: "Stone Beige", hex: "#C5B8A5" }
    ],
    image: "/tshirt-4.png",
    images: ["/tshirt-4.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Combed Micro-Textured Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 55
  },
  {
    _id: "tshirt-5",
    name: "Abstract Pink-White Printed Oversized Tee",
    slug: "abstract-pink-white-printed-oversized-tee",
    description: "Contemporary oversized streetwear tee with all-over abstract geometric art print and relaxed drop shoulders.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 135,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Abstract Pink White", hex: "#E8C5D0" },
      { name: "Monochrome Black", hex: "#111111" }
    ],
    image: "/tshirt-5.png",
    images: ["/tshirt-5.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Premium Heavy Supima Cotton (260 GSM)",
    careInstructions: "Machine wash cool inside out.",
    inStock: true,
    stockCount: 60
  },

  // HOODIES & TRACK PANTS
  {
    _id: "hoodie-1",
    name: "Aura Gold Heavyweight Hoodie",
    slug: "aura-gold-heavyweight-hoodie",
    description: "Ultra-heavyweight 480GSM French terry cotton hoodie featuring embroidered metallic gold Vyora monogram.",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    rating: 4.9,
    reviewsCount: 128,
    category: "Hoodies",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Charcoal Gray", hex: "#2E2E2E" }
    ],
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Hoodies",
    fabric: "100% Heavyweight French Terry Cotton (480 GSM)",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "trackpants-1",
    name: "Vanguard Heavy French Terry Track Pants",
    slug: "vanguard-heavy-french-terry-track-pants",
    description: "Relaxed tapered fit track pants with custom gold-tipped drawstrings, deep zip pockets, and ribbed ankle cuffs.",
    price: 799,
    originalPrice: 999,
    discount: 20,
    rating: 4.8,
    reviewsCount: 88,
    category: "Track Pants",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Heather Gray", hex: "#4A4A4A" }
    ],
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Track Pants",
    fabric: "420GSM Heavyweight Organic Cotton Fleece",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 50
  }
];
