export const sampleProducts = [
  {
    _id: "tshirt-1",
    name: "Beige Embossed Medallion Oversized T-Shirt",
    slug: "beige-embossed-medallion-oversized-tshirt",
    description: "Premium heavy cotton oversized tee with a central 3D embossed medallion emblem, drop-shoulder cut, and vintage wash finish.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 142,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Beige Tan", hex: "#D4C5B9" },
      { name: "Charcoal Fade", hex: "#3A3A3A" }
    ],
    image: "/tshirt-1.png",
    images: ["/tshirt-1.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Heavyweight Supima Organic Cotton (280 GSM)",
    careInstructions: "Machine wash cold inside out, dry flat.",
    inStock: true,
    stockCount: 65
  },
  {
    _id: "tshirt-2",
    name: "Off-White Textural Monogram Crewneck",
    slug: "offwhite-textural-monogram-crewneck",
    description: "Luxury off-white crewneck tee crafted with an all-over debossed geometric monogram texture and relaxed fit silhouette.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 5.0,
    reviewsCount: 98,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ivory Cream", hex: "#F3EAD8" },
      { name: "Onyx Black", hex: "#0F0F0F" }
    ],
    image: "/tshirt-2.png",
    images: ["/tshirt-2.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Organic Jacquard Textured Cotton",
    careInstructions: "Delicate cold wash, warm iron.",
    inStock: true,
    stockCount: 50
  },
  {
    _id: "tshirt-3",
    name: "Cream Ribbed Quarter-Zip Polo T-Shirt",
    slug: "cream-ribbed-quarter-zip-polo-tshirt",
    description: "Sophisticated ribbed knit polo shirt featuring a polished metallic ring zipper and drop-shoulder boxy cut.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.8,
    reviewsCount: 86,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Vanilla Cream", hex: "#F5F0EB" },
      { name: "Midnight Navy", hex: "#1A2332" }
    ],
    image: "/tshirt-3.png",
    images: ["/tshirt-3.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "Ribbed Premium Cotton Blend",
    careInstructions: "Machine wash gentle cold.",
    inStock: true,
    stockCount: 40
  },
  {
    _id: "tshirt-4",
    name: "Earth Brown Textured Long-Sleeve Tee",
    slug: "earth-brown-textured-long-sleeve-tee",
    description: "Earth-tone brown long-sleeve tee made from micro-textured cotton with custom atelier tag branding.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 110,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Earth Brown", hex: "#784F33" },
      { name: "Stone Beige", hex: "#C5B8A5" }
    ],
    image: "/tshirt-4.png",
    images: ["/tshirt-4.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Combed Micro-Textured Cotton",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 55
  },
  {
    _id: "tshirt-5",
    name: "Abstract Pink-White Printed Oversized Tee",
    slug: "abstract-pink-white-printed-oversized-tee",
    description: "Contemporary oversized streetwear tee with all-over abstract geometric art print and relaxed drop shoulders.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 135,
    category: "T-Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Abstract Pink White", hex: "#E8C5D0" },
      { name: "Monochrome Black", hex: "#111111" }
    ],
    image: "/tshirt-5.png",
    images: ["/tshirt-5.png"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "T-Shirts",
    fabric: "100% Premium Heavy Supima Cotton (260 GSM)",
    careInstructions: "Machine wash cool inside out.",
    inStock: true,
    stockCount: 60
  },
  {
    _id: "shirt-1",
    name: "Elegance Satin Oxford Shirt",
    slug: "elegance-satin-oxford-shirt",
    description: "Smooth silk-touch satin shirt tailored with clean lines, French cuffs, and subtle gold threading along placket.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 76,
    category: "Shirts",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ivory White", hex: "#FFFFFF" },
      { name: "Jet Black", hex: "#000000" }
    ],
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Shirts",
    fabric: "100% Micro-Luster Satin Cotton",
    careInstructions: "Delicate cycle wash, warm iron.",
    inStock: true,
    stockCount: 35
  },
  {
    _id: "hoodie-1",
    name: "Aura Gold Heavyweight Hoodie",
    slug: "aura-gold-heavyweight-hoodie",
    description: "Ultra-heavyweight 480GSM French terry cotton hoodie featuring embroidered metallic gold Vyora monogram.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.9,
    reviewsCount: 128,
    category: "Hoodies",
    gender: "Men",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Charcoal Gray", hex: "#2E2E2E" }
    ],
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Hoodies",
    fabric: "100% Heavyweight French Terry Cotton (480 GSM)",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 45
  },
  {
    _id: "trackpants-1",
    name: "Vanguard Heavy French Terry Track Pants",
    slug: "vanguard-heavy-french-terry-track-pants",
    description: "Relaxed tapered fit track pants with custom gold-tipped drawstrings, deep zip pockets, and ribbed ankle cuffs.",
    price: 599,
    originalPrice: 799,
    discount: 25,
    rating: 4.8,
    reviewsCount: 88,
    category: "Track Pants",
    gender: "Men",
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Onyx Black", hex: "#0A0A0A" },
      { name: "Heather Gray", hex: "#4A4A4A" }
    ],
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80",
    images: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=80"],
    isNewArrival: true,
    isTrending: true,
    collectionType: "Track Pants",
    fabric: "420GSM Heavyweight Organic Cotton Fleece",
    careInstructions: "Machine wash cold inside out.",
    inStock: true,
    stockCount: 50
  }
];
